core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.generic import TemplateView

from tastypie.api import Api
from reservations.api import ReservationResource
from rooms.api import RoomResource
from users.api import UserResource
from .views import Home

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(ReservationResource())
v1_api.register(RoomResource())
v1_api.register(UserResource())

urlpatterns = patterns('',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^api/', include(v1_api.urls)),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'', include('users.urls', namespace='users')),
    url(r'^room/', include('rooms.urls', namespace='rooms')),
    url(r'^reserve/', include('reservations.urls', namespace='reservations')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

rooms/urls.py
from django.conf.urls import patterns, url

from .views import RoomList, RoomCreate, RoomDelete, RoomUpdate
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', RoomList.as_view(), name='list'),

    url(r'^new/$', login_required(RoomCreate.as_view()), name='create'),
    url(r'^update/(?P<slug>[-\w]+)/$', login_required(RoomUpdate.as_view()), name='update'),
    url(r'^delete/(?P<slug>[-\w]+)/$', login_required(RoomDelete.as_view()), name='delete'),
)

rooms/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify

from django.core.validators import RegexValidator
import re

color_re = re.compile('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')
validate_color = RegexValidator(color_re, _(u'Enter a valid color.'), 'invalid')

class Room(models.Model):
    no = models.CharField(_('Room Number'), max_length=20)
    name = models.CharField(_('Room Name'), max_length=50)
    slug = models.SlugField(_("slug"), max_length=60, unique=True)
    color = models.CharField(_("Color"), max_length=10, default="#3071a9", validators=[validate_color])
    capacity = models.PositiveSmallIntegerField(_('Room Capacity'), default=0)
    desc = models.TextField(_('Room Description'), blank=True)

    created_on = models.DateTimeField(_('Created On'), default=timezone.now(), editable=False)
    updated_on = models.DateTimeField(_('Updated On'), editable=False, null=True, blank=True)

    def __unicode__(self):
        return '[%s] %s' % (self.no, self.name)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)[:50]
        self.updated_on = timezone.now()
        super(Room, self).save()

rooms/views.py
from django.views.generic import TemplateView, FormView, ListView
from django.views.generic.base import ContextMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from core.views import MessageMixin

from .models import Room

class RoomList(ListView):
    model = Room
    paginate_by = 15

class RoomCreate(MessageMixin, CreateView):
    model = Room
    success_url = reverse_lazy('rooms:list')
    message = _('Successfully Created')


class RoomUpdate(MessageMixin, UpdateView):
    model = Room
    success_url = reverse_lazy('rooms:list')
    message = _('Successfully Updated')


class RoomDelete(MessageMixin, DeleteView):
    model = Room
    success_url = reverse_lazy('rooms:list')
    message = _('Successfully Deleted')

templates/rooms/room_confirm_delete.html
{% extends 'base_confirm_delete.html' %}
{% load i18n %}

{% block panel-heading %}{% trans 'Room' %}{% endblock %}
{% block object-name %}{% trans 'Room' %} {{ object }} {% endblock %}

{% block backlink %}{% url 'rooms:list' %}{% endblock %}

templates/rooms/room_form.html
{% extends 'base_form.html' %}
{% load i18n %}
{% block header-title %}{% trans 'Room' %}{% endblock %}
{% block backlink %}{% url 'rooms:list' %}{% endblock %}

templates/rooms/room_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block header-title %}{% trans 'Room' %}{% endblock %}

{% block content %}

<div class="clear-fix"></div>
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
        {% trans 'Room List' %} 
        </div>

    <!-- Table -->
    <table class="table table-hover table-striped">
    <thead>
        <th>#</th>
        <th>{% trans 'Room#' %}</th>
        <th>{% trans 'Room Name' %}</th>
        <th>{% trans 'Capacity' %}</th>
        <th>{% trans 'Description' %}</th>
    </thead>
    <tbody>
    {% for room in object_list %}
    <tr>
        <td style="background-color:{{room.color}}">{{forloop.counter}}</td>
        <td>{{room.no}}</td>
        <td>{{room.name}}</td>
        <td>{{room.capacity}}</td>
        <td>
            {% if user.is_staff %}
                <a href="{% url 'rooms:update' room.slug %}" class="btn btn-xs btn-info">Edit</a>
                <a href="{% url 'rooms:delete' room.slug %}" class="btn btn-xs btn-danger">Delete</a>
            {% endif %}
            {{room.desc}}</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="4">{% trans 'N/A' %}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pager">
        {% if page_obj.has_previous %}
            <li><a href="{% url 'rooms:list' %}?page={{ page_obj.previous_page_number }}">&laquo; Previous</a></li>
        {% endif %}
            <li>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</li>
        {% if page_obj.has_next %}
            <li><a href="{% url 'rooms:list' %}?page={{ page_obj.next_page_number }}">Next &raquo;</a></li>
        {% endif %}
    </ul>
    {% endif %}
</div>

{% if user.is_staff %}
<span><a href="{% url 'rooms:create' %}" class="btn btn-primary">{% trans 'New' %}</a></span>
{% endif %}
{% endblock %}