core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.generic import TemplateView

from tastypie.api import Api
from reservations.api import ReservationResource
from rooms.api import RoomResource
from users.api import UserResource
from .views import Home

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(ReservationResource())
v1_api.register(RoomResource())
v1_api.register(UserResource())

urlpatterns = patterns('',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^api/', include(v1_api.urls)),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'', include('users.urls', namespace='users')),
    url(r'^room/', include('rooms.urls', namespace='rooms')),
    url(r'^reserve/', include('reservations.urls', namespace='reservations')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

reservations/urls.py
from django.conf.urls import patterns, url

from .views import ReservationList, ReservationCreate, ReservationDelete, ReservationUpdate
from .views import PendingReservationList, ReservationHistory, ReservationReport
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', ReservationList.as_view(), name='list'),
    url(r'^pending/$', PendingReservationList.as_view(), name='pending-list'),
    url(r'^all/$', ReservationHistory.as_view(), name='history'),
    url(r'^report/(?P<pk>\d+)/$', ReservationReport.as_view(), name='report'),
    # url(r'^pending/update/(?P<pk>\d+)/$', ApprovingReservationUpdate.as_view(), name='pending-update'),

    url(r'^new/$', login_required(ReservationCreate.as_view()), name='create'),
    url(r'^update/(?P<pk>\d+)/$', login_required(ReservationUpdate.as_view()), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', login_required(ReservationDelete.as_view()), name='delete'),
)

rooms/urls.py
from django.conf.urls import patterns, url

from .views import RoomList, RoomCreate, RoomDelete, RoomUpdate
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', RoomList.as_view(), name='list'),

    url(r'^new/$', login_required(RoomCreate.as_view()), name='create'),
    url(r'^update/(?P<slug>[-\w]+)/$', login_required(RoomUpdate.as_view()), name='update'),
    url(r'^delete/(?P<slug>[-\w]+)/$', login_required(RoomDelete.as_view()), name='delete'),
)

users/urls.py
from django.conf.urls import patterns, url

from .views import CreateUser, UserProfile, UserList
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^private/$', 'users.views.private', name='private'),
    url(r'^register/$', CreateUser.as_view(), name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', 'users.views.logout_user', name='logout'),

    url(r'^profile/(?P<pk>\d+)/$', login_required(UserProfile.as_view()), name='profile'),
    url(r'^users/$', login_required(UserList.as_view()), name='list'),
)

templates/base.html
{% load static from staticfiles %}
{% load compress %}{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{% block title %}{{ SITE_NAME }}{% endblock %}</title>
        {% compress css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/sticky-footer-navbar.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}"/>
        <link rel='stylesheet' href='{% static "fullcalendar-1.6.3/fullcalendar.css" %}'/>
        <link rel='stylesheet' href='{% static "fullcalendar-1.6.3/fullcalendar.print.css" %}' media='print' />
        <link rel="stylesheet" href="{% static 'css/application.css' %}"/>
        {% endcompress %}
        {% compress css inline %}
        {% block extra_css %}{% endblock %}
        {% endcompress %}
        <!-- End CSS -->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="../../assets/js/html5shiv.js"></script>
          <script src="../../assets/js/respond.min.js"></script>
        <![endif]-->

        <!-- Start JavaScript Variables -->
        <script>
        var apiLimitPerPage = 0{{ API_LIMIT_PER_PAGE }},
            errors = {% if not messages %}null,{% else %}[
                {% for message in messages %}{
                    tags: "{{ message.tags }}",
                    text: "{{ message }}"
                }{% endfor %}
            ],{% endif %}
            currentUser = {
                id: "{{ user.id }}",
                username: "{{ user.username }}",
                gravatar: "{{ user.gravatar }}"
            },
            tagFilter = "{{ request.resolver_match.kwargs.tag }}",
            userFilter = "{{ request.resolver_match.kwargs.user }}";
        </script>
        <!-- End JavaScript Variables -->
    </head>

    <body>
    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">{{ SITE_NAME }}</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home' %}">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            {% if user.is_staff %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Management <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'users:list' %}">{% trans 'Users' %}</a></li>
                <li><a href="{% url 'rooms:list' %}">{% trans 'Rooms' %}</a></li>
                <li><a href="{% url 'reservations:history' %}">{% trans 'Request' %}</a></li>
              </ul>
            </li>
            {% endif %}

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user }} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'users:profile' user.pk %}">{% trans 'Profile' %}</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">ACTION</li>
                {% if user.is_superuser %}
                <li><a href="/admin/">{% trans 'Admin' %}</a></li>
                {% endif %}
                <li><a href="{% url 'auth_password_change' %}">Password Change</a></li>
                <li><a href="{% url 'users:logout' %}">{% trans 'Logout' %}</a></li>
              </ul>
            </li>
            {% else %}
            <li><a href="{% url 'users:login' %}">{% trans 'Login' %}</a></li>
            <li><a href="{% url 'users:register' %}">{% trans 'Register' %}</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
      </div>

      <!-- Begin page content -->
      <div class="container">
        {% block header %}
        <div class="page-header">
          <h1>{% block header-title %}{% endblock %}</h1>
        </div>
        {% endblock %}
        <div class="row">
            <div class="col-md-3">
                <div class="hidden-print panel panel-success" role="complementary">
                  <div class="panel-heading">{% trans 'Information' %}</div>
                  <ul class="panel-body nav">
                    <li class=""><a href="{% url 'home' %}">{% trans 'Room Schedule' %}</a></li>
                    <li class=""><a href="{% url 'rooms:list' %}">{% trans 'Room Detail' %}</a></li>
                  </ul>
                </div>
            {% if user.is_authenticated %}
                <div class="hidden-print panel panel-info" role="complementary">
                  <div class="panel-heading">{% trans 'Request' %}</div>
                  <ul class="panel-body nav">
                    <li class=""><a href="{% url 'reservations:create' %}">{% trans 'Make A Reservation' %}</a></li>
                    <li class=""><a href="{% url 'reservations:list' %}">{% trans 'Request Status' %}</a></li>
                    {% if user.is_staff %}
                    <li class=""><a href="{% url 'reservations:pending-list' %}">{% trans 'Pending Request' %} <span class="label label-sm label-default">{{pending_items}}</span></a></li>
                    {% endif %}
                  </ul>
                </div>
            {% endif %}
            </div>
            <div class="col-md-9">
              {% block content %}
                <p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added within <code>#wrap</code> with <code>padding-top: 60px;</code> on the <code>.container</code>.</p>
                <p>Back to <a href="../sticky-footer">the default sticky footer</a> minus the navbar.</p>
              {% endblock %}
            </div>
        </div>

      </div>
    </div>


    <div id="footer">
      <div class="container">
        <p class="text-muted credit"> <a href="http://twitter.com/sipp11">@sipp11</a> with <a href="http://zzyzx.co/">Zzyzx Co.,Ltd.</a></p>
      </div>
    </div>
        <!-- Templates -->
        {% include "includes/messages.html" %}
        {% block extra_templates %}{% endblock %}
        <!-- End Templates -->

        <!-- JavaScript -->
        {% compress js %}
        <script src='{% static "js/jquery.min.js" %}'></script>
        <script src='{% static "js/handlebars.min.js" %}'></script>
        <script src='{% static "js/helpers.js" %}'></script>
        <script src='{% static "js/messages.js" %}'></script>
        <script src='{% static "js/bootstrap.min.js" %}'></script>
        <script src='{% static "fullcalendar-1.6.3/fullcalendar.min.js" %}'></script>
        <script src='{% static "js/underscore.js" %}'></script>
        <script src='{% static "js/backbone.js" %}'></script>
        <script src='{% static "js/calendar_app.js" %}'></script>
        <script src='{% static "js/backbone-tastypie.js" %}'></script>
        <script>
            $(document).ready(function($) {
                // $('input').addClass('form-control');
            });
            // sending a csrftoken with every ajax request
            // token
            !function ($) {
              $.ajaxSetup({
                   beforeSend: function(xhr, settings) {
                       function getCookie(name) {
                           var cookieValue = null;
                           if (document.cookie && document.cookie != '') {
                               var cookies = document.cookie.split(';');
                               for (var i = 0; i < cookies.length; i++) {
                                   var cookie = jQuery.trim(cookies[i]);
                                   // Does this cookie string begin with the name we want?
                               if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                   cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                   break;
                               }
                           }
                       }
                       return cookieValue;
                       }
                       if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                           // Only send the token to relative URLs i.e. locally.
                           xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                       }
                   }
              });

            }(window.jQuery)
        </script>
        <!-- JS
        <script src="{% static "js/helpers.js" %}"></script>
        <script src="{% static "js/lightbox.js" %}"></script>
        <script src="{% static "js/pinry.js" %}"></script>
        <script src="{% static "js/pin-form.js" %}"></script>
        -->
        {% endcompress %}
        {% compress js inline %}
        {% block extra_js %}{% endblock %}
        {% endcompress %}
        <!-- End JavaScript -->
    </body>
</html>

templates/base_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="row">

    <div id="form" class="panel panel-default panel-danger">
      <div class="panel-heading">{% block panel-heading %}{% trans 'Register' %}{% endblock %}</div>
      <div class="panel-body">


        <form action="" method="post">{% csrf_token %}
            <h4>{% trans 'Are you sure you want to delete' %} 
                {% block object-name %}{% endblock %}?</h4>

            <div class="btn-group btn-group-lg">
                <a class="btn btn-default" href="{% block backlink %}{% endblock %}">{% trans 'Cancel' %}</a>
                <button type="submit" class="btn btn-danger">{% trans 'Confirm' %}</button>
            </div>
        </form>
      </div>
    </div>

</div>

{% endblock %}

templates/base_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="row">

    <div id="form" class="panel panel-default {% block panel-class %}{% endblock %}">
      <div class="panel-heading">{% block panel-heading %}{% endblock %}</div>
      <div class="panel-body">


        <form action="{% block form-action %}{% endblock %}" method="post">{% csrf_token %}
        {% block form-container %}
        
        {% for field in form %}
            {% include "includes/field.html" %}
        {% endfor %}

        {% endblock %}

          <div class="btn-group btn-group-lg">
              <a class="btn btn-default" href="{% block backlink %}{% endblock %}">{% trans 'Cancel' %}</a>
              <button type="submit" class="btn btn-success">
                {% block form-submit %}{% trans 'Update' %}{% endblock %}</button>
          </div>
        </form>
      </div>
    </div>

</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}{% load i18n %}

{% block page-header %}{% trans 'Reservation System' %}{% endblock %}
{% block content %}

<div id='calendar'></div>

<ul class="list-unstyled">
{% for room in rooms %}
<li><span style="background-color:{{room.color}}; border:1px solid #ddd">&nbsp;&nbsp;&nbsp;&nbsp;</span> {{room}}</li>
{% empty %}
{% endfor %}
</ul>

{% endblock %}