core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.generic import TemplateView

from tastypie.api import Api
from reservations.api import ReservationResource
from rooms.api import RoomResource
from users.api import UserResource
from .views import Home

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(ReservationResource())
v1_api.register(RoomResource())
v1_api.register(UserResource())

urlpatterns = patterns('',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^api/', include(v1_api.urls)),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'', include('users.urls', namespace='users')),
    url(r'^room/', include('rooms.urls', namespace='rooms')),
    url(r'^reserve/', include('reservations.urls', namespace='reservations')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

reservations/urls.py
from django.conf.urls import patterns, url

from .views import ReservationList, ReservationCreate, ReservationDelete, ReservationUpdate
from .views import PendingReservationList, ReservationHistory, ReservationReport
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', ReservationList.as_view(), name='list'),
    url(r'^pending/$', PendingReservationList.as_view(), name='pending-list'),
    url(r'^all/$', ReservationHistory.as_view(), name='history'),
    url(r'^report/(?P<pk>\d+)/$', ReservationReport.as_view(), name='report'),
    # url(r'^pending/update/(?P<pk>\d+)/$', ApprovingReservationUpdate.as_view(), name='pending-update'),

    url(r'^new/$', login_required(ReservationCreate.as_view()), name='create'),
    url(r'^update/(?P<pk>\d+)/$', login_required(ReservationUpdate.as_view()), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', login_required(ReservationDelete.as_view()), name='delete'),
)

reservations/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from schedule.models.events import Event

STATUS_PENDING = 'p'
STATUS_ACKNOWLEDGE = 'k'
STATUS_ACCEPTED = 'a'
STATUS_REJECTED = 'r'

class Reservation(Event):
    STATUS_CHOICES = (
        (STATUS_PENDING, _('Pending')),
        (STATUS_ACKNOWLEDGE, _('Acknowledged')),
        (STATUS_ACCEPTED, _('Accepted')),
        (STATUS_REJECTED, _('Rejected')),
    )
    room = models.ForeignKey('rooms.room', related_name='Room')

    approval_status = models.CharField(_('Approval Status'), max_length=1, choices=STATUS_CHOICES, default=STATUS_PENDING)
    approver = models.ForeignKey('users.user', related_name='Approval Officer', blank=True, null=True)
    approved_on = models.DateTimeField(_('Approved On'), editable=False, null=True, blank=True)
    approval_note = models.CharField(_('Approval Note'), max_length=140, blank=True, 
                                        help_text=_('maximum 140 characters'))

    updated_on = models.DateTimeField(_('Updated On'), editable=False, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.end < self.start:
            temp = self.start
            self.start = self.end
            self.end = temp

        self.updated_on = timezone.now()
        super(Reservation, self).save()

    def is_pending(self):
        return True if self.approval_status in (STATUS_PENDING, STATUS_ACKNOWLEDGE) else False

    def is_reviewed(self):
        return True if self.approval_status in (STATUS_ACCEPTED, STATUS_REJECTED) else False

    def get_period(self):
        return self.end - self.start

reservations/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        exclude = ['approval_note']
        widgets = {
            'created_on': forms.HiddenInput(),
            'approval_status': forms.HiddenInput(),
            'approver': forms.HiddenInput(),
            'approved_on': forms.HiddenInput(),
            'rule': forms.HiddenInput(),
            'calendar': forms.HiddenInput(),
            'creator': forms.HiddenInput(),
            'end_recurring_period': forms.HiddenInput(),
        }


class ApprovingReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        exclude = ['title', 'room', 'creator', 'start', 'end', 'description',
                    'created_on', 'rule', 'calendar', 'end_recurring_period']
        widgets = {
            'approver': forms.HiddenInput(),
            'approved_on': forms.HiddenInput(),
        }

reservations/views.py
from django.views.generic import TemplateView, FormView, ListView, View
from django.views.generic.base import ContextMixin
from django.views.generic.list import MultipleObjectMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy as _

from .models import Reservation
from .forms import ReservationForm, ApprovingReservationForm

from core.views import MessageMixin
from braces.views import StaffuserRequiredMixin
import time
from datetime import date

class ReservationReport(StaffuserRequiredMixin, TemplateView):
    model = Reservation
    template_name = 'reservations/report.html'

    def get_context_data(self, **kwargs):
        context = super(ReservationReport, self).get_context_data(**kwargs)
        context['item'] = Reservation.objects.get(pk=kwargs.get('pk'))
        context['duration'] = (context['item'].end - context['item'].start)
        context['today'] = date.today()
        print context['item'].creator.username
        return context


class ReservationHistory(StaffuserRequiredMixin, TemplateView):
    model = Reservation
    template_name = 'reservations/history.html'

    def get_context_data(self, **kwargs):
        context = super(ReservationHistory, self).get_context_data(**kwargs)
        context['object_list'] = Reservation.objects.all().order_by('start')
        return context


class PendingReservationList(StaffuserRequiredMixin, MultipleObjectMixin, TemplateView):
    template_name = 'reservations/pending_list.html'
    paginate_by = 15
    queryset = None
    model = Reservation

    def get_queryset(self):
        self.queryset = Reservation.objects.filter(approval_status__in=['p', 'k'])
        return super(PendingReservationList, self).get_queryset(self)

    def get_context_data(self, **kwargs):
        context = {'object_list': Reservation.objects.filter(approval_status__in=['p', 'k'])}
        context.update(kwargs)
        return super(PendingReservationList, self).get_context_data(**context)


class ReservationList(ListView):
    model = Reservation
    paginate_by = 15

    def get_queryset(self):
        queryset = super(ReservationList, self).get_queryset()
        return queryset.filter(creator=self.request.user)


class ReservationCreate(MessageMixin, CreateView):
    model = Reservation
    form_class = ReservationForm
    success_url = reverse_lazy('reservations:list')
    message = _('Successfully Created')

    def get_form_kwargs(self):
        kwargs = super(ReservationCreate, self).get_form_kwargs()
        kwargs.update({'initial': {'creator': self.request.user } })
        return kwargs


class ReservationUpdate(MessageMixin, UpdateView):
    model = Reservation
    form_class = ReservationForm
    success_url = reverse_lazy('reservations:list')
    message = _('Successfully Updated')


class ReservationDelete(MessageMixin, DeleteView):
    model = Reservation
    success_url = reverse_lazy('reservations:list')
    message = _('Successfully Deleted')

templates/reservations/history.html
{% extends 'base.html' %}
{% load i18n %}{% load static %}

{% block header-title %}{% trans 'Reservation History' %}{% endblock %}

{% block content %}

<div class="clear-fix"></div>
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"></div>

    <!-- Table -->
    <table class="table table-hover table-striped">
    <thead>
        <th>#</th>
        <th>{% trans 'Title' %}</th>
        <th>{% trans 'Room' %}</th>
        <th>{% trans 'Status' %}</th>
    </thead>
    <tbody>
    {% for e in object_list %}
    <tr class="{% if e.approval_status == 'k' %}warning{% elif e.approval_status == 'a' %}success{% elif e.approval_status == 'r'%}danger{% endif %}">
        <td>{{forloop.counter}}</td>
        <td>{{e.title}}</td>
        <td>{{e.room}}</td>
        <td>
            {{e.get_approval_status_display}} 
            <span class="label label-xs label-default">{% trans 'By' %}</span>
            {{ e.approver }} on {{ e.approved_on }}
            {% if e.approval_note %}
                <br/><span class="label label-xs label-info">{% trans 'Reason' %}</span>
                {{e.approval_note}}
            {% endif %}
        </td>
    </tr>
    <tr>
        <td></td>
        <td colspan="4">
            <span class="label label-xs label-default">{% trans 'Requested By' %}</span> {{e.creator}}
            <span class="label label-xs label-default">{% trans 'Period' %}</span> {{e.get_period}}
            <span class="label label-xs label-default">{% trans 'Time' %}</span> {{e.start}} - {{e.end}}
            <p>{{e.desc}}</p>
            <p class="f"></p>
        </td>
    {% empty %}
    <tr>
        <td colspan="4">{% trans 'N/A' %}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
</div>

<p>{% trans 'Status' %}:
    <span style="background-color:#fafafa; border:1px solid #ddd">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Pending' %}
    <span style="background-color:#fcf8e3; border:1px solid #fbeed5">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Acknowledged' %}
    <span style="background-color:#dff0d8">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Accepted' %}
    <span style="background-color:#f2dede">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Rejected' %}
</p>

{% endblock %}

templates/reservations/pending_list.html
{% extends 'base.html' %}
{% load i18n %}{% load static %}

{% block header-title %}{% trans 'Reservation' %}{% endblock %}

{% block content %}

<div class="clear-fix"></div>
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
        {% trans 'Pending List' %} 
        </div>

    <!-- Table -->
    <table class="table table-hover table-striped">
    <thead>
        <th>#</th>
        <th>{% trans 'Title' %}</th>
        <th>{% trans 'Room' %}</th>
        <th>{% trans 'User' %}</th>
        <th>{% trans 'Action' %}</th>
    </thead>
    <tbody>
    {% for e in object_list %}
    <tr class="{% if e.approval_status == 'k' %}warning{% elif e.approval_status == 'a' %}success{% elif e.approval_status == 'r'%}danger{% endif %}">
        <td>{{forloop.counter}}</td>
        <td>{{e.title}}</td>
        <td>{{e.room}}</td>
        <td>{{e.creator}}</td>
        <td>
            <a href="{% url 'reservations:report' e.pk %}" class="btn btn-xs btn-primary">{% trans 'Print Report' %}</a>
            <span class="action_button">
                <button class="btn btn-xs btn-success action" data-action="accept" data-id='{{e.pk}}'>{% trans 'Accepted' %}</button>
                <button class="btn btn-xs btn-danger action" data-action="reject" data-id='{{e.pk}}'>{% trans 'Rejected' %}</button>
            </span>
        </td>
    </tr>
    <tr>
        <td></td>
        <td colspan="4">
            <span class="label label-xs label-info">{% trans 'Period' %}</span> {{e.get_period}}
            <span class="label label-xs label-info">{% trans 'Time' %}</span> {{e.start}} - {{e.end}}
            <p>{{e.desc}}</p>
            <p class="f"></p>
        </td>
    {% empty %}
    <tr>
        <td colspan="4">{% trans 'N/A' %}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    {% if is_paginated %}
    <ul class="pager">
        {% if page_obj.has_previous %}
            <li><a href="{% url 'reservations:pending-list' %}?page={{ page_obj.previous_page_number }}">&laquo; Previous</a></li>
        {% endif %}
            <li>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</li>
        {% if page_obj.has_next %}
            <li><a href="{% url 'reservations:pending-list' %}?page={{ page_obj.next_page_number }}">Next &raquo;</a></li>
        {% endif %}
    </ul>
    {% endif %}
</div>

<p>{% trans 'Status' %}:
    <span style="background-color:#fafafa; border:1px solid #ddd">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Pending' %}
    <span style="background-color:#fcf8e3; border:1px solid #fbeed5">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Acknowledged' %}
    <span style="background-color:#dff0d8">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Accepted' %}
    <span style="background-color:#f2dede">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Rejected' %}
</p>

{% endblock %}

{% block extra_templates %}
{% include "includes/approving_form.html" %}
{% endblock %}

{% block extra_js %}
<script>
function dismissForm(form) {
    if (!form) var form = $('#approving-form');
    form.fadeOut(400);
    setTimeout(function() {
        form.remove();
    }, 400);
}

$().ready(function() {
    $('.action').click(function(evt) {
        var id = $(this).attr('data-id'),
            btn = $(this),
            btn_txt = $(this).html(),
            action = $(this).attr('data-action'),
            tr_parent = $(this).closest('tr');
        btn.attr('disabled', 'disabled').html('processing...');
        var promise = getReservationData(id);
        promise.success(function(data) {
            dismissForm();

            var template = Handlebars.compile($('#approving-template').html());
            var html = template(data);

            var d = btn.closest('tr').next().find('p.f');
            d.html('').hide().append(html).fadeIn(200);

            if (action == 'accept') {
                d.find('option[value="a"]').attr('selected', true);
            } else {
                d.find('option[value="r"]').attr('selected', true);
                d.find('#approving-form-save').addClass('btn-danger');
            }

            d.find('#approving-form-dismiss').click(function(e) { dismissForm(); });
            d.find('#approving-form-save').click(function(e) { 
                var newData = {
                    resource_uri: d.find('input[name=resource_uri]').val(),
                    approval_status: d.find('#id_approval_status').val(),
                    approver: '/api/v1/user/'+{{user.pk}}+'/',
                    approved_on: new Date(),
                };
                if (d.find('#id_approval_note').val() != "") {
                    newData['approval_note'] = d.find('#id_approval_note').val();
                }

                var save_promise = updateReservationData(id, newData);
                save_promise.success(function(res) {
                    dismissForm();
                    switch (action) {
                        case 'accept': tr_parent.removeClass('warning').addClass('success'); break;
                        case 'reject': tr_parent.removeClass('warning').addClass('danger'); break;
                    }
                    tr_parent.find('.action_button').hide();
                });
                save_promise.error(function(err) {
                    dismissForm();
                });

            });

            btn.attr('disabled', false).html(btn_txt);
            message('Successfully executed.', 'alert alert-success');
        });
        promise.error(function(error) {
            console.log(error);
            btn.attr('disabled', false).html(btn_txt);
            message('Problem!! Try again.', 'alert alert-error');
        });
    });

});

</script>

{% endblock %}

templates/reservations/report.html
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="/static/css/bootstrap.min.css" media='screen,print'/>
<style>

@font-face {
  font-family: 'THSaranbun';
  src: local('THSaranbun Bold'), local('THSaranbun-Bold'), url('/static/fonts/thsarabun-bold.woff') format('woff');
  src: local('THSaranbun'), local('THSaranbun'), url('/static/fonts/thsarabun.woff') format('woff');
}

body { font-family: 'THSaranbun';font-size: 18px;}
</style>

</head>

<body>

<div class="container">




<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 text-center">
        <h4>บันทึกข้อความ</h4>
    </div>
</div>

<p><strong>ส่วนราชการ</strong>     คณะวิทยาการจัดการ มหาวิทยาลัยราชภัฏนครราชสีมา</p>
<p><strong>ที่</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;วันที่ {{today|date:'j'}} เดือน {{today|date:'F'}} พ.ศ. {{today|date:'Y'}}</p>
<p><strong>เรื่อง</strong> &nbsp;&nbsp;&nbsp;&nbsp;ขออนุญาตใช้อาคารสถานที่คณะวิทยาการจัดการ</p>
<p><strong>เรียน</strong> &nbsp;&nbsp;&nbsp;&nbsp;หัวหน้าสำนักงานคณบดี</p>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ข้าพเจ้า {%if item.creator.get_full_name %}{{item.creator.get_full_name}}{% else %}{{item.creator.username}}{% endif %} ตำแหน่ง ..............................  หน่วยงาน............................ โทรศัพท์ภายใน................................................... มีความประสงค์ขออนุญาตใช้อาคารสถานที่</p>
    </div>
</div>
<div class="row">
    <div class="col-sm-1 col-md-1 col-lg-1">   </div>
    <div class="col-sm-11 col-md-11 col-lg-11">
        <ul class="list-unstyled">
            <li><span class="glyphicon glyphicon-unchecked"></span> ห้องประชุมวิทยาการจัดการ 1 (22.14)</li>
            <li><span class="glyphicon glyphicon-unchecked"></span> ห้องประชุมหน้าห้องประชุมวิทยาการจัดการ 1 (22.14)</li>
            <li><span class="glyphicon glyphicon-unchecked"></span> ห้องประชุมวิทยาการจัดการ 2 (22.11)</li>
            <li><span class="glyphicon glyphicon-unchecked"></span> ห้องประชุมวิทยาการจัดการ 4 (ภาษาเกาหลี)</li>
            <li><span class="glyphicon glyphicon-unchecked"></span> ห้องประชุมวิทยาการจัดการ 5 </li>
            <li><span class="glyphicon glyphicon-unchecked"></span> ห้องประชุมวิทยาการจัดการ 7 (13.11)</li>
            <li><span class="glyphicon glyphicon-unchecked"></span> ห้องประชุมวิทยาการจัดการ 8 (ห้องการแสดง)</li>
            <li><span class="glyphicon glyphicon-unchecked"></span> ห้องอื่น ๆ  ระบุ..................................................................</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-lg-7">
        <ul class="list-unstyled list-inline">
            <li><strong>เพื่อวัตถุประสงค์</strong></li>
            <li><span class="glyphicon glyphicon-unchecked"></span> ประชุม</li>
            <li><span class="glyphicon glyphicon-unchecked"></span> สอบ</li>
            <li><span class="glyphicon glyphicon-unchecked"></span> การเรียนการสอน</li>
            <li><span class="glyphicon glyphicon-unchecked"></span> อื่นๆ</li>
        </ul>
    </div>
</div>


<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        จำนวนผู้เข้าร่วมประชุม ........... คน    อาจารย์ ............. คน บุคคลภายนอก .............. คน นักศึกษา ............. คน
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        ในวันที่ {{item.start|date:'j'}} เดือน {{item.start|date:'M'}} พ.ศ. {{item.start|date:'Y'}} ตั้งแต่เวลา {{item.start|date:'H:j:i'}} ถึง {{item.end|date:'H:j:i'}} น. 
        {% if duration %}
        และ/ถึงวันที่ {{item.end|date:'j'}} เดือน  {{item.end|date:'M'}}  พ.ศ. {{item.end|date:'Y'}} ตั้งแต่เวลา {{item.start|date:'H:j:i'}} ถึง {{item.end|date:'H:j:i'}} น. 
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-sm-1 col-md-1 col-lg-1">   </div>
    <div class="col-sm-11 col-md-11 col-lg-11">
        <p>จึงเรียนมาเพื่อโปรดพิจารณา</p>
    </div>
</div>

<div class="row">
    <div class="col-sm-5 col-md-5 col-lg-5"></div>
    <div class="col-sm-7 col-md-7 col-lg-7 text-center">
        ลงชื่อ............................................................ผู้ขออนุญาต<br/>
            ( {%if item.creator.get_full_name %}{{item.creator.get_full_name}}{% else %}{{item.creator.username}}{% endif %} )
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 text-center">
        <h6><u>หมายเหตุ</u>  :  หากต้องการใช้อุปกรณ์โสตทัศนูปกรณ์  โปรดใช้แบบฟอร์มขออนุญาตต่างหาก</h6>
    </div>
</div>

</div>


</body>
</html>

templates/reservations/reservation_confirm_delete.html
{% extends 'base_confirm_delete.html' %}
{% load i18n %}

{% block panel-heading %}{% trans 'Reservation' %}{% endblock %}
{% block object-name %}{% trans 'Reservation' %} {{ object }} {% endblock %}

{% block backlink %}{% url 'reservations:list' %}{% endblock %}

templates/reservations/reservation_form.html
{% extends 'base_form.html' %}
{% load i18n %}{% load static %}
{% block header-title %}{% trans 'Reservation' %}{% endblock %}
{% block backlink %}{% url 'reservations:list' %}{% endblock %}

{% block extra_css %}<link rel="stylesheet" href="{% static 'css/will_pickdate.css' %}"/>{% endblock %}
{% block extra_js %}
<script src="{% static 'js/will_pickdate.js' %}"></script>
<script src="{% static 'js/jquery.mousewheel.js' %}"></script>
<script>
$('input[name=start]').will_pickdate({
  timePicker: true,
  format: 'Y-m-d H:i:s',
  inputOutputFormat: 'Y-m-d H:i:s'
});
$('input[name=end]').will_pickdate({
  timePicker: true,
  format: 'Y-m-d H:i:s',
  inputOutputFormat: 'Y-m-d H:i:s'
});
</script>
{% endblock %}

templates/reservations/reservation_list.html
{% extends 'base.html' %}
{% load i18n %}{% load static %}

{% block header-title %}{% trans 'Reservation' %}{% endblock %}

{% block content %}

<div class="clear-fix"></div>
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
        {% trans 'Your Reservation List' %} 
        </div>

    <!-- Table -->
    <table class="table table-hover table-striped">
    <thead>
        <th>#</th>
        <th>{% trans 'Title' %}</th>
        <th>{% trans 'Room' %}</th>
        <th>{% trans 'Period' %}</th>
        <th>{% trans 'Time' %}</th>
        <th>{% trans 'Description' %}</th>
    </thead>
    <tbody>

    {% for e in object_list %}
    <tr class="{% if e.approval_status == 'k' %}warning{% elif e.approval_status == 'a' %}success{% elif e.approval_status == 'r'%}danger{% endif %}">
        <td>{{forloop.counter}}</td>
        <td>{{e.title}}</td>
        <td>{{e.room}}</td>
        <td>{{e.get_period}}</td>
        <td>{{e.start}}
            <span class="label label-xs label-default">to</span><br/> {{e.end}}</td>
        <td>
            {% if e.is_pending %}
            <a href="{% url 'reservations:update' e.pk %}" class="btn btn-xs btn-info">{% trans 'Edit' %}</a>
            <a href="{% url 'reservations:delete' e.pk %}" class="btn btn-xs btn-danger">{% trans 'Delete' %}</a>
            {% endif %}
            <br/>{{e.desc}} </td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="4">{% trans 'N/A' %}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pager">
        {% if page_obj.has_previous %}
            <li><a href="{% url 'reservations:list' %}?page={{ page_obj.previous_page_number }}">&laquo; Previous</a></li>
        {% endif %}
            <li>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</li>
        {% if page_obj.has_next %}
            <li><a href="{% url 'reservations:list' %}?page={{ page_obj.next_page_number }}">Next &raquo;</a></li>
        {% endif %}
    </ul>
    {% endif %}
</div>

<p>{% trans 'Status' %}:
    <span style="background-color:#fafafa; border:1px solid #ddd">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Pending' %}
    <span style="background-color:#fcf8e3; border:1px solid #fbeed5">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Acknowledged' %}
    <span style="background-color:#dff0d8">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Accepted' %}
    <span style="background-color:#f2dede">&nbsp;&nbsp;&nbsp;&nbsp;</span> {% trans 'Rejected' %}
</p>

{% endblock %}